### ISSUE TITLE
Add new quotes to the list of possible quotes

### ISSUE THREAD

**Issue by tshin7** [shintouki/random-quote-machine#6]
**Is your feature request related to a problem? Please describe.**

This feature request is not related to a problem.

**Describe the solution you'd like**

- It would be nice to have a larger list of quotes to draw a random quote from. 
- To achieve this, add some new quotes to the [quotes array](https://github.com/tshin7/random-quote-machine/blob/gh-pages/js/index.js#L20-L90) (at most 5).

**Describe alternatives you've considered**

A more robust solution would be to query a random quote from a quote api, but this is out of scope for this feature request.

**Comment by aadamczykode** [comment]
I'd like to take this issue.

**Comment by tshin7** [comment]
> I'd like to take this issue.

Sure! Go ahead. Let me know if you have any questions.
